# Generated by Django 6.1 on 2026-08-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='link',
        ),
    ]
