# Generated by Django 6.1 on 2026-08-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notifications_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
